MONGODB_CONFIG:
  name: "testData"          # 自定义次数据库链接名称
  type: "mongodb"                      # 数据库链接类型
  url: "mongodb://127.0.0.1:27017"   # 数据库链接地址
  port: 27017
  # username: ""                   # 数据库链接用户名
  # password: ""                 # 数据库链接密码
  database: "testData"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
  useUnifiedTopology: true
REDIS_CONFIG:
  host: "124.223.219.30"  # redis 链接
  port: 6379         # redis 端口
  auth: "root"       # redis 连接密码
  db: 1              # redis 数据库
